"""empty message

Revision ID: c9c47d3eb6d4
Revises: 957ab6516981
Create Date: 2023-01-30 15:43:31.619088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c47d3eb6d4'
down_revision = '957ab6516981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
